apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: craftista-microservices
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: craftista
    app.kubernetes.io/instance: production
spec:
  project: craftista

  # Source configuration
  source:
    repoURL: https://github.com/akhileshmishrabiz/may-bootcamp.git
    path: class28-29/microservices-on-k8s/k8s-menifest-adv
    targetRevision: HEAD

    # Kustomize configuration
    kustomize:
      namePrefix: ""
      nameSuffix: ""
      images:
        - 339713040609.dkr.ecr.ap-south-1.amazonaws.com/frontend:latest
        - 339713040609.dkr.ecr.ap-south-1.amazonaws.com/catalogue:latest
        - 339713040609.dkr.ecr.ap-south-1.amazonaws.com/voting:latest
        - 339713040609.dkr.ecr.ap-south-1.amazonaws.com/recco:latest

      commonLabels:
        deployed-by: argocd
        environment: production

  # Destination
  destination:
    server: https://kubernetes.default.svc
    namespace: craftista

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Health checks
  ignoreDifferences:
    - group: apps
      kind: Deployment
      managedFieldsManagers:
        - kube-controller-manager
    - group: ""
      kind: Secret
      name: craftista-tls-secret
      namespace: craftista

  # Revision history limit
  revisionHistoryLimit: 10
