apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: craftista-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: craftista-app-of-apps
spec:
  project: default  # Using default project for meta-application
  
  # Source configuration
  source:
    repoURL: https://github.com/akhileshmishrabiz/may-bootcamp.git
    path: class24-eks/microservices-on-k8s/argocd-apps
    targetRevision: HEAD
    
    # Directory configuration
    directory:
      recurse: false
      include: "*.yaml"
      exclude: "01-argocd-namespace.yaml,02-argocd-install.yaml,05-app-of-apps.yaml"
  
  # Destination
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m