apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: craftista-tls
  namespace: craftista
spec:
  secretName: craftista-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ms.akhileshmishra.tech
  dnsNames:
  - ms.akhileshmishra.tech
  - '*.ms.akhileshmishra.tech'
  - catalogue.ms.akhileshmishra.tech
  - voting.ms.akhileshmishra.tech
  - recommendations.ms.akhileshmishra.tech
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days before expiry
  subject:
    organizations:
    - craftista
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
  - digital signature
  - key encipherment
  - server auth