apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: craftista
  labels:
    app: catalogue
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalogue
  template:
    metadata:
      labels:
        app: catalogue
        tier: backend
    spec:
      containers:
      - name: catalogue
        image: 879381241087.dkr.ecr.ap-south-1.amazonaws.com/devopsbootcamp-dev-catalogue:v20251011-f7cc7797
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: catalogue-db-secrets
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: catalogue-db-secrets
              key: db_password
        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: catalogue-config
              key: app_version
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.json
          subPath: config.json
        - name: db-config-volume
          mountPath: /app/db-config
        - name: db-secrets-volume
          mountPath: /app/secrets
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: config-volume
        configMap:
          name: catalogue-config
          items:
          - key: config.json
            path: config.json
      - name: db-config-volume
        configMap:
          name: catalogue-config
          items:
          - key: db-config.properties
            path: db-config.properties
      - name: db-secrets-volume
        secret:
          secretName: catalogue-db-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: craftista
  labels:
    app: catalogue
spec:
  type: ClusterIP
  selector:
    app: catalogue
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
