apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: craftista
  labels:
    app: frontend
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: 339713040609.dkr.ecr.ap-south-1.amazonaws.com/frontend:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: CATALOGUE_URL
          value: "http://catalogue:5000"
        - name: RECOMMENDATION_URL
          value: "http://recco:8080"
        - name: VOTING_URL
          value: "http://voting:8080"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: craftista
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http