apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: craftista
  labels:
    app: catalogue
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalogue
  template:
    metadata:
      labels:
        app: catalogue
        tier: backend
    spec:
      containers:
      - name: catalogue
        image: 339713040609.dkr.ecr.ap-south-1.amazonaws.com/catalogue:latest
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: DB_HOST
          value: "craftista-db.cdglnjeympmt.ap-south-1.rds.amazonaws.com"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: DB_NAME
          value: "catalogue"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: craftista
  labels:
    app: catalogue
spec:
  type: ClusterIP
  selector:
    app: catalogue
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http