apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    # Production Let's Encrypt server
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@akhileshmishra.tech  # Change this to your email
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    # HTTP01 solver for domain validation
    - http01:
        ingress:
          class: alb
      selector:
        dnsNames:
        - 'ms.akhileshmishra.tech'
        - '*.ms.akhileshmishra.tech'
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    # Staging Let's Encrypt server for testing
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@akhileshmishra.tech  # Change this to your email
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    # HTTP01 solver for domain validation
    - http01:
        ingress:
          class: alb
      selector:
        dnsNames:
        - 'ms.akhileshmishra.tech'
        - '*.ms.akhileshmishra.tech'