apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting
  namespace: craftista
  labels:
    app: voting
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voting
  template:
    metadata:
      labels:
        app: voting
        tier: backend
    spec:
      containers:
      - name: voting
        image: 339713040609.dkr.ecr.ap-south-1.amazonaws.com/voting:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: DB_HOST
          value: "craftista-db.cdglnjeympmt.ap-south-1.rds.amazonaws.com"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: DB_NAME
          value: "voting"
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: voting
  namespace: craftista
  labels:
    app: voting
spec:
  type: ClusterIP
  selector:
    app: voting
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http