apiVersion: apps/v1
kind: Deployment
metadata:
  name: recco
  namespace: craftista
  labels:
    app: recco
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recco
  template:
    metadata:
      labels:
        app: recco
        tier: backend
    spec:
      containers:
      - name: recco
        image: livingdevopswithakhilesh/microservices:recommendation-644625f8de627843afd6fc916bc30459705c2726
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: recco
  namespace: craftista
  labels:
    app: recco
spec:
  type: ClusterIP
  selector:
    app: recco
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http