apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: craftista
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Craftista microservices project
  
  # Source repositories
  sourceRepos:
    - 'https://github.com/akhileshmishrabiz/may-bootcamp.git'
    - 'https://github.com/akhileshmishrabiz/may-bootcamp'
    - '*'  # Allow all repositories for flexibility
  
  # Destinations
  destinations:
    - namespace: craftista
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  
  # Cluster resource allow list
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: cert-manager.io
      kind: ClusterIssuer
  
  # Namespace resource allow list
  namespaceResourceWhitelist:
    - group: ''
      kind: Service
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: PersistentVolumeClaim
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: apps
      kind: ReplicaSet
    - group: networking.k8s.io
      kind: Ingress
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: cert-manager.io
      kind: Certificate
    - group: cert-manager.io
      kind: Issuer
  
  # RBAC roles
  roles:
    - name: craftista-admin
      description: Full access to craftista project
      policies:
        - p, proj:craftista:craftista-admin, applications, *, craftista/*, allow
        - p, proj:craftista:craftista-admin, repositories, *, *, allow
        - p, proj:craftista:craftista-admin, certificates, *, *, allow
      groups:
        - craftista-admins
    
    - name: craftista-developer
      description: Developer access to craftista project
      policies:
        - p, proj:craftista:craftista-developer, applications, get, craftista/*, allow
        - p, proj:craftista:craftista-developer, applications, sync, craftista/*, allow
        - p, proj:craftista:craftista-developer, repositories, get, *, allow
      groups:
        - craftista-developers

  # Sync windows (optional - for maintenance windows)
  syncWindows:
    - kind: allow
      schedule: '* * * * *'
      duration: 24h
      applications:
        - '*'
      manualSync: true
    - kind: deny
      schedule: '0 2 * * *'  # Deny automatic sync at 2 AM (maintenance window)
      duration: 1h
      applications:
        - '*'
      manualSync: false