apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  # RBAC Policy
  policy.default: role:readonly
  policy.csv: |
    # Admin role - full access
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:admin, projects, *, *, allow
    p, role:admin, certificates, *, *, allow
    
    # Developer role - craftista project access
    p, role:craftista-developer, applications, get, craftista/*, allow
    p, role:craftista-developer, applications, sync, craftista/*, allow
    p, role:craftista-developer, applications, action/*, craftista/*, allow
    p, role:craftista-developer, applications, override, craftista/*, allow
    p, role:craftista-developer, repositories, get, *, allow
    p, role:craftista-developer, repositories, create, *, allow
    p, role:craftista-developer, repositories, update, *, allow
    p, role:craftista-developer, projects, get, craftista, allow
    
    # DevOps role - infrastructure management
    p, role:devops, applications, *, */*, allow
    p, role:devops, clusters, *, *, allow
    p, role:devops, repositories, *, *, allow
    p, role:devops, projects, *, *, allow
    p, role:devops, certificates, *, *, allow
    
    # Read-only role
    p, role:readonly, applications, get, */*, allow
    p, role:readonly, clusters, get, *, allow
    p, role:readonly, repositories, get, *, allow
    p, role:readonly, projects, get, *, allow
    
    # Group assignments (can be updated based on your org structure)
    g, akhilesh, role:admin
    g, craftista-team, role:craftista-developer
    g, devops-team, role:devops
    g, viewers, role:readonly
    
    # Project-specific policies
    p, proj:craftista:admin, applications, *, craftista/*, allow
    p, proj:craftista:admin, repositories, *, *, allow
    p, proj:craftista:developer, applications, get, craftista/*, allow
    p, proj:craftista:developer, applications, sync, craftista/*, allow
    
  # SCOPES for different actions
  scopes: '[groups, email]'

---
# Secret for GitHub access (update with your credentials)
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: argocd
type: Opaque
stringData:
  username: "your-github-username"  # Update this
  password: "your-github-token"     # Update with GitHub personal access token

---
# Service Account for ArgoCD with additional permissions
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-application-controller
  namespace: argocd

---
# ClusterRole for ArgoCD to manage cert-manager resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-cert-manager-controller
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - certificaterequests
  - clusterissuers
  - issuers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - acme.cert-manager.io
  resources:
  - challenges
  - orders
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

---
# ClusterRoleBinding for cert-manager permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-cert-manager-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-cert-manager-controller
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: argocd