name: class30 infra scan 

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TF_VER: 1.5.7
  infra_path: class30/infra

jobs:
  terraform:
    name: Terraform Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3   

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VER }}
      - name: terraform fmt
        run: terraform fmt -check -recursive ${{ env.infra_path }}

      - name: Run Checkov scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ${{ env.infra_path }}
          framework: terraform
          quiet: false
          output: cli
          # skip_check: CKV2_AWS_11